### ISSUE TITLE
replace_pair in learn_bpe.py throws exception for strings that end with escape char (backslash)

### ISSUE THREAD

**Issue by dblandan** [rsennrich/subword-nmt#5]
pair 1920: \pccsrv \ -> \pccsrv\ (frequency 2798)
Traceback (most recent call last):
  File "./learn_bpe.py", line 201, in <module>
    changes = replace_pair(most_frequent, sorted_vocab, indices)
  File "./learn_bpe.py", line 145, in replace_pair
    new_word = pattern.sub(pair_str, new_word)
  File "/usr/lib/python2.7/re.py", line 273, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python2.7/re.py", line 260, in _compile_repl
    raise error, v # invalid expression
sre_constants.error: bogus escape (end of line)

**Comment by rsennrich** [comment]
thanks for the report - this should be fixed.

**Comment by dblandan** [comment]
Quicker than I was fixing locally!  :-)   Thanks very much.

cheers,
-dave

**Comment by dblandan** [comment]
Sorry, still throws error for me.  I was thinking along the lines for if
the string ends in a single backslash, replace with two, but not sure
whether there are downstream consequences.

cheers,
-d

**Comment by rsennrich** [comment]
Can you give me an example line that fails? I tested and fixed the following line:

abc ab\def cb\def fb\xyz

after your last comment, I also tested this, which works:

abc ab\\def cb\\def fb\\

**Comment by rsennrich** [comment]
[the last line is supposed to have double backslashes everywhere; which got escaped by the comment system]

**Comment by dblandan** [comment]
copy file regsvr32.exe from \system32 to \pccsrv\lwcs

There are several occurrences of paths involving pccsrv in the corpus, so
it looks like it's trying to decompose \pccsrv\ unsuccessfully...  (I
*think*...  but now I'm starting to doubt myself)

**Comment by rsennrich** [comment]
I tested learn_bpe.py on a toy corpus consisting of your line twice, and this works for me.

If this fails for you, which python version are you using? Could you please also double-check if your repo's working directory is clean and contains the fixed version of learn_bpe.py?

**Comment by dblandan** [comment]
OK, sorry.  works for me now.  I must've munged something somewhere.  clean
git clone did the trick.  :-)

thanks again!!
-d
